package tarea_2;

/**
 *
 * @author brecinosm
 */

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
public class frm_principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_principal
     */
    public frm_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_datos = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_respuesta1 = new javax.swing.JLabel();
        lbl_respuesta2 = new javax.swing.JLabel();
        lbl_respuesta3 = new javax.swing.JLabel();
        lbl_respuesta4 = new javax.swing.JLabel();
        lbl_respuesta5 = new javax.swing.JLabel();
        lbl_respuesta6 = new javax.swing.JLabel();
        lbl_respuesta7 = new javax.swing.JLabel();
        lbl_respuesta8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_respuesta9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_respuesta10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_respuesta11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_respuesta12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_respuesta13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_respuesta14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_respuesta15 = new javax.swing.JLabel();
        lbl_respuesta16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        item_abrir = new javax.swing.JMenuItem();
        item_guardar = new javax.swing.JMenuItem();
        item_guardarcomo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROGRAMACION II");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(275, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MANEJO DE CADENAS");

        jLabel2.setText("Ingrese un texto o abra un archivo");

        txt_datos.setColumns(20);
        txt_datos.setRows(5);
        jScrollPane2.setViewportView(txt_datos);

        jButton1.setText("PROCESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Longitud del texto...:");

        jLabel4.setText("Total de palabras...:");

        jLabel5.setText("Primera letra del texto...:");

        jLabel6.setText("Ultima letra del texto...:");

        jLabel7.setText("Letra central del texto...:");

        jLabel8.setText("Primera palabra...:");

        jLabel9.setText("Palabra central...:");

        jLabel10.setText("Ultima palabra...:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("TRADUCCION A CLAVE MURCIELAGO");

        jLabel12.setText("Repeticiones de \"A\", \"a\", \"á\"...:");

        jLabel13.setText("Repeticiones de \"E\", \"e\", \"é\"...:");

        jLabel14.setText("Repeticiones de \"I\", \"i\", \"í\"...:");

        jLabel15.setText("Repeticiones de \"O\", \"o\", \"ó\"...:");

        jLabel16.setText("Repeticiones de \"U\", \"u\", \"ú\"...:");

        jLabel17.setText("Palabras con caracter par...:");

        jLabel18.setText("Palabras con caracter Impar...:");

        lbl_respuesta16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu3.setText("Archivo");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        item_abrir.setText("Abrir");
        item_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_abrirActionPerformed(evt);
            }
        });
        jMenu3.add(item_abrir);

        item_guardar.setText("Guardar");
        item_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_guardarActionPerformed(evt);
            }
        });
        jMenu3.add(item_guardar);

        item_guardarcomo.setText("Guardar Como");
        item_guardarcomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_guardarcomoActionPerformed(evt);
            }
        });
        jMenu3.add(item_guardarcomo);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Editar");

        jMenuItem4.setText("Copiar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Cortar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Pegar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Buscar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Remplazar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_respuesta8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_respuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_respuesta6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_respuesta7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_respuesta15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_respuesta14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_respuesta13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_respuesta12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_respuesta11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_respuesta10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_respuesta9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(lbl_respuesta16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel11)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbl_respuesta9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbl_respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel13)
                                                    .addComponent(lbl_respuesta10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(lbl_respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel15))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_respuesta11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbl_respuesta12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(lbl_respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel16)
                                    .addComponent(lbl_respuesta13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_respuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17)
                            .addComponent(lbl_respuesta14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_respuesta6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lbl_respuesta7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_respuesta15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(lbl_respuesta8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_respuesta16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void traducirTexto() {
    
        String textoOriginal = txt_datos.getText();
    String correspondencia = "abcdefghijklmnñopqrstuvwxyz";
    String reemplazos = "7b3d5f8h4jk60nñ9pq2st1vwxyz";

    StringBuilder textoTraducido = new StringBuilder();

    for (char c : textoOriginal.toCharArray()) {
        int index = correspondencia.indexOf(Character.toLowerCase(c));
        if (index != -1) {
            char reemplazo = reemplazos.charAt(index);
            if (Character.isUpperCase(c)) {
                textoTraducido.append(Character.toUpperCase(reemplazo));
            } else {
                textoTraducido.append(reemplazo);
            }
        } else {
            textoTraducido.append(c);
        }
    }

    lbl_respuesta16.setText(textoTraducido.toString());
}

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            
        traducirTexto();
        // Longitud del texto
        String text = txt_datos.getText();
        int longitud = text.length();
        lbl_respuesta1.setText(String.valueOf(longitud));

        // Total de palabras
        String text1 = txt_datos.getText();
        String[] palabras = text1.split("\\s+");
        int totalPalabras = palabras.length;
        lbl_respuesta2.setText(String.valueOf(totalPalabras));

        // Primera letra del texto
        String text2 = txt_datos.getText();

        if (!text2.isEmpty()) {
            char primeraLetra = text2.charAt(0);
            lbl_respuesta3.setText(String.valueOf(primeraLetra));
        } else {
            lbl_respuesta3.setText("Texto vacío");
        }

        // Ultima palabra del texto
        String text3 = txt_datos.getText();

        if (!text3.isEmpty()) {
            char ultimaLetra = text3.charAt(text3.length() - 1);
            lbl_respuesta4.setText(String.valueOf(ultimaLetra));
        } else {
            lbl_respuesta4.setText("Texto vacío");
        }

        // Letra central del texto
        String text4 = txt_datos.getText();

        if (!text4.isEmpty()) {
            int longitud1 = text4.length();
            int posicionCentral = longitud1 / 2;

            char letraCentral = text4.charAt(posicionCentral);
            lbl_respuesta5.setText(String.valueOf(letraCentral));
        } else {
            lbl_respuesta5.setText("Texto vacío");
        }

        // Primera palabra
        String text5 = txt_datos.getText();

        if (!text5.isEmpty()) {
            String[] palabras1 = text5.split("\\s+");
            if (palabras1.length > 0) {
                String primeraPalabra1 = palabras1[0];
                lbl_respuesta6.setText(primeraPalabra1);
            } else {
                lbl_respuesta6.setText("No hay palabras");
            }
        } else {
            lbl_respuesta6.setText("Texto vacío");
        }

        // Palabra central
        String text6 = txt_datos.getText();

        if (!text6.isEmpty()) {
            String[] palabras2 = text6.split("\\s+");
            int totalPalabras2 = palabras2.length;

            if (totalPalabras2 > 0) {
                int posicionCentral = totalPalabras2 / 2;
                String palabraCentral = palabras2[posicionCentral];
                lbl_respuesta7.setText(palabraCentral);
            } else {
                lbl_respuesta7.setText("No hay palabras");
            }
        } else {
            lbl_respuesta7.setText("Texto vacío");
        }

        // Ultima palabra
        String text7 = txt_datos.getText();

        if (!text7.isEmpty()) {
            String[] palabras3 = text7.split("\\s+");
            int totalPalabras3 = palabras3.length;

            if (totalPalabras3 > 0) {
                String ultimaPalabra3 = palabras3[totalPalabras - 1];
                lbl_respuesta8.setText(ultimaPalabra3);
            } else {
                lbl_respuesta8.setText("No hay palabras");
            }
        } else {
            lbl_respuesta8.setText("Texto vacío");
        }

        // Contar repeticiones de "A", "a" y "á" en el texto
        String text8 = txt_datos.getText();

        int contadorA = 0;

        for (int i = 0; i < text8.length(); i++) {
            char caracter = text8.charAt(i);
            if (caracter == 'A' || caracter == 'a' || caracter == 'á' || caracter == 'Á') {
                contadorA++;
            }
        }

        lbl_respuesta9.setText(String.valueOf(contadorA));

        // Contar repeticiones de "E", "e" y "é" en el texto
        String text9 = txt_datos.getText();

        int contadorE = 0;

        for (int i = 0; i < text9.length(); i++) {
            char caracter1 = text9.charAt(i);
            if (caracter1 == 'E' || caracter1 == 'e' || caracter1 == 'é' || caracter1 == 'É') {
                contadorE++;
            }
        }

        lbl_respuesta10.setText(String.valueOf(contadorE));

        // Contar repeticiones de "I", "i" y "í" en el texto
        String text10 = txt_datos.getText();

        int contadorI = 0;

        for (int i = 0; i < text10.length(); i++) {
            char caracter2 = text10.charAt(i);
            if (caracter2 == 'I' || caracter2 == 'i' || caracter2 == 'í' || caracter2 == 'Í') {
                contadorI++;
            }
        }

        lbl_respuesta11.setText(String.valueOf(contadorI));

        // Contar repeticiones de "O", "o" y "ó" en el texto
        String text11 = txt_datos.getText();

        int contadorO = 0;

        for (int i = 0; i < text11.length(); i++) {
            char caracter3 = text11.charAt(i);
            if (caracter3 == 'O' || caracter3 == 'o' || caracter3 == 'ó' || caracter3 == 'Ó') {
                contadorO++;
            }
        }

        lbl_respuesta12.setText(String.valueOf(contadorO));

        // Contar repeticiones de "U", "u" y "ú" en el texto
        String text12 = txt_datos.getText();

        int contadorU = 0;

        for (int i = 0; i < text12.length(); i++) {
            char caracter4 = text12.charAt(i);
            if (caracter4 == 'U' || caracter4 == 'u' || caracter4 == 'ú' || caracter4 == 'Ú') {
                contadorU++;
            }
        }

        lbl_respuesta13.setText(String.valueOf(contadorU));

        // Contar palabras con cantidad de caracteres par en el texto
        String text13 = txt_datos.getText();
        String[] palabras5 = text13.split("\\s+");
        int contadorPalabrasPar = 0;

        for (String palabra5 : palabras5) {
            if (palabra5.length() % 2 == 0) {
                contadorPalabrasPar++;
            }
        }

        lbl_respuesta14.setText(String.valueOf(contadorPalabrasPar));

        // Contar palabras con cantidad de caracteres impar en el texto
        String text14 = txt_datos.getText();
        String[] palabras6 = text14.split("\\s+");

        int contadorPalabrasImpar = 0;

        for (String palabra6 : palabras6) {
            if (palabra6.length() % 2 != 0) {
                contadorPalabrasImpar++;
            }
        }

        lbl_respuesta15.setText(String.valueOf(contadorPalabrasImpar));
         

    }//GEN-LAST:event_jButton1ActionPerformed

    private void item_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_abrirActionPerformed
        // TODO add your handling code here:
    JFileChooser fileChooser = new JFileChooser();
    
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto (.txt)", "txt");
    fileChooser.setFileFilter(filter);
    
    int result = fileChooser.showOpenDialog(this);
    
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        
        try {
            BufferedReader reader = new BufferedReader(new FileReader(selectedFile));
            String line;
            StringBuilder fileContent = new StringBuilder();

            while ((line = reader.readLine()) != null) {
                fileContent.append(line).append("");
            }

            reader.close();

            txt_datos.setText(fileContent.toString());  // Mostrar contenido en el JTextArea
            archivoActual = selectedFile;  // Establecer el archivo actual
        } catch (IOException e) {
            e.printStackTrace();
}
}
    }//GEN-LAST:event_item_abrirActionPerformed

    private File archivoActual = null;
    private void item_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_guardarActionPerformed
        // TODO add your handling code here:
        if (archivoActual != null) {
        guardarArchivo(archivoActual);
    } else {
        JFileChooser fileChooser = new JFileChooser();
        
        int result = fileChooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            guardarArchivo(selectedFile);
        }
    }

    }//GEN-LAST:event_item_guardarActionPerformed
 private void guardarArchivo(File archivo) {
    try {
        FileWriter writer = new FileWriter(archivo);
        String content = txt_datos.getText();
        writer.write(content);
        writer.close();
        archivoActual = archivo;
    } catch (IOException e) {
        e.printStackTrace();
}
}

    private void item_guardarcomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_guardarcomoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
    
    int result = fileChooser.showSaveDialog(this);
    
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        
        try {
            FileWriter writer = new FileWriter(selectedFile);
            
            // Obtener el contenido del JTextArea
            String content = txt_datos.getText();
            
            // Escribir el contenido en el archivo
            writer.write(content);
            
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
}
}       
    }//GEN-LAST:event_item_guardarcomoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        // COPIAR
    String selectedText = txt_datos.getSelectedText();

    if (selectedText != null && !selectedText.isEmpty()) {
        // Copiar el texto al portapapeles
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection selection = new StringSelection(selectedText);
        clipboard.setContents(selection, null);
    }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // PEGAR
        
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    Transferable contents = clipboard.getContents(null);

    if (contents != null && contents.isDataFlavorSupported(DataFlavor.stringFlavor)) {
        try {
            // Obtener el contenido del portapapeles como texto
            String clipboardText = (String) contents.getTransferData(DataFlavor.stringFlavor);

            // Pegar el contenido en el JTextArea
            int caretPosition = txt_datos.getCaretPosition();
            txt_datos.insert(clipboardText, caretPosition);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // CORTAR
        
                String selectedText = txt_datos.getSelectedText();

    if (selectedText != null && !selectedText.isEmpty()) {
        // Copiar el texto al portapapeles
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection selection = new StringSelection(selectedText);
        clipboard.setContents(selection, null);

        // Eliminar el texto seleccionado del JTextArea
        int start = txt_datos.getSelectionStart();
        int end = txt_datos.getSelectionEnd();
        txt_datos.replaceRange("", start, end);
    }

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // BUSCAR
        
                 String searchText = JOptionPane.showInputDialog(this, "Buscar:");
    if (searchText != null) {
        String content = txt_datos.getText();
        int startIndex = 0;
        int occurrences = 0;
        
        while (startIndex != -1) {
            startIndex = content.indexOf(searchText, startIndex);
            if (startIndex != -1) {
                txt_datos.setCaretPosition(startIndex);
                txt_datos.setSelectionStart(startIndex);
                txt_datos.setSelectionEnd(startIndex + searchText.length());
                startIndex += searchText.length();
                occurrences++;
            }
        }
        
        if (occurrences == 0) {
            JOptionPane.showMessageDialog(this, "Texto no encontrado.");
 }
 }

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // REMPLAZAR
        
                  String searchText = JOptionPane.showInputDialog(this, "Buscar:");
    if (searchText != null) {
        String replaceText = JOptionPane.showInputDialog(this, "Reemplazar con:");
        if (replaceText != null) {
            String content = txt_datos.getText();
            String newContent = replaceAllOccurrences(content, searchText, replaceText);
            txt_datos.setText(newContent);
        }
    };
    }                                               

    private String replaceAllOccurrences(String originalText, String searchText, String replaceText) {
    StringBuilder result = new StringBuilder();
    int startIndex = 0;
    int foundIndex;

    while ((foundIndex = originalText.indexOf(searchText, startIndex)) != -1) {
        result.append(originalText, startIndex, foundIndex);
        result.append(replaceText);
        startIndex = foundIndex + searchText.length();
    }

    result.append(originalText, startIndex, originalText.length());

    return result.toString();

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_abrir;
    private javax.swing.JMenuItem item_guardar;
    private javax.swing.JMenuItem item_guardarcomo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_respuesta1;
    private javax.swing.JLabel lbl_respuesta10;
    private javax.swing.JLabel lbl_respuesta11;
    private javax.swing.JLabel lbl_respuesta12;
    private javax.swing.JLabel lbl_respuesta13;
    private javax.swing.JLabel lbl_respuesta14;
    private javax.swing.JLabel lbl_respuesta15;
    private javax.swing.JLabel lbl_respuesta16;
    private javax.swing.JLabel lbl_respuesta2;
    private javax.swing.JLabel lbl_respuesta3;
    private javax.swing.JLabel lbl_respuesta4;
    private javax.swing.JLabel lbl_respuesta5;
    private javax.swing.JLabel lbl_respuesta6;
    private javax.swing.JLabel lbl_respuesta7;
    private javax.swing.JLabel lbl_respuesta8;
    private javax.swing.JLabel lbl_respuesta9;
    private javax.swing.JTextArea txt_datos;
    // End of variables declaration//GEN-END:variables
}
